---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guanxiaoda.
--- DateTime: 2018/1/17 下午12:49
---

local key = KEYS[1] --限流KEY
local interval = tonumber(ARGV[1]) --请求间隔
local expire = tonumber(ARGV[2])
local current = tonumber(ARGV[3])
local last = tonumber(redis.call('get', key) or 0)

if current - last >= interval  then
    -- 超过间隔，放行，并设置2秒过期
    redis.call("set", key, current)
    redis.call("expire", key, expire)
    return 1
else
    return 0
end