server:
  port: 8301
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
spring:
  application:
    name: scheduler

rate:
  path: scripts/rateLimiter.lua
  key: redis_rate_limiter_key
  lianjia:
    mobile: 0.1