server:
  port: 8301
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
spring:
  application:
    name: scheduler
  datasource:
    url: jdbc:mysql://127.0.0.1/spider_db?characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver


  jpa:
    show-sql: true
    database: mysql

rate:
  path: scripts/rateLimiter.lua
  key: redis_rate_limiter_key
  common: 5

logging:
  file: logs/scheduler.log