## spring ##
spring:
  application:
    name: crawlerengine
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
mysql:
  url: jdbc:mysql://127.0.0.1/spider_db?characterEncoding=utf8
  user: root
  pwd:

## project ##
mq:
  receive:
    interval: 100
  topic:
    parser:
      task:
        list: mq_parse_task_list
        detail: mq_parse_task_detail
    crawler:
      task:
        test: mq_crawl_task_test
scheduler:
  url: 172.30.5.156:8301/scheduler
proxy:
  api:
    kdl: none
  fetchRate:
    kdl: 4.9

thread:
  fetcher: 20
  parser: 20
  storager: 20



#debug: true
debug: false


logging:
  file: logs/engine.log
